[package]
name = "lemon-lisp"
version = "0.1.0"
edition = "2021"

[lib]
name = "lemon_lisp"
path = "src/lib.rs"

[dependencies]
rug = "1.22.0"
rustyline = { version = "14.0.0", features = ["derive"] }
